# defaults for uat
apims:
  api:
    mock-implementations-allowed: true
  app:
    config-profile: uat
    config-profile-prefix: uat
    env: uat
    namespace: uat
    resource-prefix: uat
  integration:
    endpoints:
      apimsdb-server: "apims-db.uat.nc.gcp.internal.skycdp.de:5432"
      toolsdb-server: "tools-db.uat.nc.gcp.internal.skycdp.de:5432"
      couchbase-servers: "couchbases://cb-nc01-ew3.nc01.svc.ew3-a.uat.cbms.gcp.internal.skycdp.de"
      kafka-servers: "kafka-001.uat.nc.gcp.internal.skycdp.de:9093,kafka-002.uat.nc.gcp.internal.skycdp.de:9093,kafka-003.uat.nc.gcp.internal.skycdp.de:9093,kafka-004.uat.nc.gcp.internal.skycdp.de:9093,kafka-005.uat.nc.gcp.internal.skycdp.de:9093,kafka-006.uat.nc.gcp.internal.skycdp.de:9093"
      kafka-schema-servers: "https://kafka-001.uat.nc.gcp.internal.skycdp.de:8084,https://kafka-002.uat.nc.gcp.internal.skycdp.de:8084,https://kafka-003.uat.nc.gcp.internal.skycdp.de:8084,https://kafka-004.uat.nc.gcp.internal.skycdp.de:8084,https://kafka-005.uat.nc.gcp.internal.skycdp.de:8084,https://kafka-006.uat.nc.gcp.internal.skycdp.de:8084"
      crm-gateway-instance-url: "https://uat-p.sky.com"
      cms-contentstack-instance-url: "http://svc-contentstack-datasync-api-server.ns-frontend-uat:3000"
      marketing-cloud-instance-url: "https://mc3g5c-g6r45z9ljssp7p6r1rk24.rest.marketingcloudapis.com"
      netflix-partner-instance-url: "https://partnerapi.sandbox.netflix.com"
      salesforce-instance-url: "https://skyde--uat.my.salesforce.com"
      tibco-aopd-instance-url: "https://aopd.tibco.uat.fo.gcp.internal.skycdp.de"
      tibco-orchestrator-instance-url: "https://orchestrator.tibco.uat.fo.gcp.internal.skycdp.de"
      tibco-scms-instance-url: "http://10.96.111.22:9140"
      vlocity-instance-url: "https://api.uatskysf.skyde.dc.vloc-dev.com"
      vlocity-token-url: "https://vlocity-dc-nonprod2-skyde.auth.eu-central-1.amazoncognito.com/oauth2/token"
  kafka:
    consumer:
      group-id: uat-${apims.app.name}
management:
  endpoints:
    web:
      exposure:
        include: health, heapdump, threaddump, loggers, info, prometheus, flyway
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
spring:
  couchbase:
    bucket: "uat"
    username: "uat-${apims.app.domain}-apims"
    password: ""
    scopename: "${apims.app.domain}"
  datasource:
    schema: "${apims.app.domain}"
    username: "uat-${apims.app.domain}-apims"
  kafka:
    consumer:
      group-id: uat-${apims.app.name}-default
    listener:
      concurrency: 2
  postresql:
    username: "uat-${apims.app.domain}-apims"
    password: ""
