# defaults for local test
apims:
  aspects:
    new-trace-id-enabled: false
  app:
    config-profile: dev-unit-test
    config-profile-prefix: dev-unit-test
    service-startup-listener-enabled: false
    mocks:
      api-token-mock-enabled: true
      async-mock-enabled: true
      couchbase-mock-enabled: true
      gcp-mock-enabled: true
      kafka-mock-enabled: true
      postgresql-mock-enabled: true
      resttemplate-mock-enabled: true
      repository-mock-enabled: true
      webservicetemplate-mock-enabled: true
      sftp-mock-enabled: true
      embedded-sftp-server-enabled: false
      embedded-ssh-server-enabled: false
      tasking-mock-enabled: true
      web-auth-mock-enabled: true
      mock-file-header-checksum-enabled: false
  api:
    mock-implementations-allowed: true
    salesforce:
      instance-url-locator-impl: "ApimsSalesforceInstanceUrlLocatorConfigImpl"
      instance-url: "https://skyde--devskysf1.my.salesforce.com"
      job-complete-waiting-sleep-time-millis: 0
  caching:
    enabled: false
  couchbase:
    caching:
      enabled: false
  cli:
    show-help-as-default: false
    shutdown-after-main-execution: false
  rest:
    auto-validate-request: true
  sftp:
    host: "127.0.0.1"
    download-file-min-age-seconds: 0
    channel-properties:
      security-scan-wait-sleep-time-millis: 1
      security-scan-wait-max-time-millis: 1000
  sftp-2:
    host: "127.0.0.1"
    download-file-min-age-seconds: 0
    channel-properties:
      security-scan-wait-sleep-time-millis: 1
      security-scan-wait-max-time-millis: 1000
  ssh:
    host: "127.0.0.1"
  startup-check:
    check-forbidden-application-properties: true
  trace:
    force-record-trace-files: false
  web:
    auth:
      test-token-validator:
        enabled: true
logging:
  level:
    de.sky.newcrm: DEBUG
    de.sky.newcrm.apims.spring.core.env.ApimsApplicationReadyHandler: INFO
    org.springframework.boot.test: ERROR
    root: INFO
management:
  otlp:
    tracing:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 0
spring:
  cloud:
    vault:
      enabled: false
  datasource:
    initialization-mode: none
    driver-class-name: "org.h2.Driver"
    database: "test"
    schema: "test"
    url: "jdbc:h2:mem:${spring.datasource.database};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS ${spring.datasource.schema}\\;SET SCHEMA=${spring.datasource.schema}\\;"
    username: "test"
    password: "test"
  flyway:
    enabled: false
  jpa:
    hibernate.ddl-auto: create
  kafka:
    properties:
      allow.auto.create.topics: false
    listener:
      auto-startup: false
  main:
    banner-mode: "off"
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
